In [19]:
import pandas as pd 
import numpy as np

In [20]:
datas = pd.date_range('20190101', periods = 60, freq = 'D')

df = pd.DataFrame(np.random.randn(60, 5), index = datas, columns = list("ABDCE"))

In [21]:
df

                   A         B         D         C         E
2019-01-01  0.111416  0.006918  1.588159  0.633591 -0.518574
2019-01-02 -1.518250  2.507258  0.702467  0.317387 -0.991721
2019-01-03  0.843329  0.417273  1.471881  0.092212  0.350613
2019-01-04  0.155155  0.432690 -0.343179 -0.863025 -0.404969
2019-01-05  1.088454 -0.350057  1.541270  1.009635  0.850226
2019-01-06  1.603226  0.153579  1.565917  0.718555  1.816141
2019-01-07 -1.306833 -0.597524 -0.175347 -1.110990  0.467794
2019-01-08  1.055358  0.213915 -0.143741  1.571102 -0.781199
2019-01-09 -1.482818  0.661813  0.733995  0.397556  0.821253
2019-01-10  1.303259  0.392932  0.365818  0.086197  0.895103
2019-01-11 -0.624323 -0.510356  0.456074 -1.828303 -1.302972
2019-01-12  1.640171  0.622274 -1.158850  0.430788 -1.161643
2019-01-13  0.581331  1.125686 -0.866457  1.421796  0.353079
2019-01-14  0.434366  0.642006 -1.001932  0.223331 -1.322373
2019-01-15 -1.241906 -0.896917 -2.549503  0.115943  1.444284
2019-01-16  1.835023  0.560078  1.032684  0.302270 -0.529789
2019-01-17 -0.874358 -0.703602 -2.164161 -0.509257 -1.250895
2019-01-18 -1.154140  0.857789  1.239455 -0.799702 -0.408749
2019-01-19  0.523384 -0.848025 -0.844232 -0.362599 -1.223686
2019-01-20  0.778159 -0.009133  0.552068  1.331865 -2.740306
2019-01-21  0.261236 -0.884125  0.573206 -0.532206 -0.127586
2019-01-22  0.844414  0.490242  0.209747  0.841251 -1.851385
2019-01-23  2.018771  1.340353 -0.514892  1.110466 -1.214233
2019-01-24 -0.590661  0.632784  1.419447 -0.540189  0.241935
2019-01-25  1.805676 -0.239450  1.185251 -0.166183 -1.004582
2019-01-26  1.058356  0.274076 -1.477420 -0.565588  0.914927
2019-01-27 -1.010448 -0.733963  0.160791 -0.831296  0.361066
2019-01-28 -0.227129  1.269629 -1.213567 -1.178905  1.167650
2019-01-29 -3.389752 -1.432752 -0.243193  0.811482 -0.838627
2019-01-30  0.846061 -1.090074 -0.595651 -0.122081 -1.607270
2019-01-31 -1.210626 -0.351689  0.000788  0.249385 -0.221661
2019-02-01  0.320558  1.315141 -1.112738  0.075485 -0.641175
2019-02-02  0.002696 -0.733324  0.010175 -0.254468 -0.328669
2019-02-03 -0.559704 -0.760697 -0.340022 -0.526066  0.798391
2019-02-04  1.396016 -1.232260  0.270611 -0.743717  0.439987
2019-02-05 -0.589496  0.162884 -0.787107 -0.009882  0.163886
2019-02-06 -0.012012 -0.556156  0.560739  0.600325  0.107971
2019-02-07  0.145543  1.579913  1.543731 -2.356622  0.309235
2019-02-08  0.950932 -0.321291 -0.907409  0.687715 -1.038975
2019-02-09  1.147952  0.581821  3.083746 -0.130997  1.105205
2019-02-10  1.385582  0.804410 -0.958235 -0.798667  0.697343
2019-02-11 -0.676924 -1.013777 -0.554140  0.468807 -0.901721
2019-02-12 -1.296520 -0.938633  0.073211  1.146531  0.775687
2019-02-13 -1.409668  3.257201 -0.372407  0.354055 -0.076574
2019-02-14 -0.511498 -2.189097 -0.466224  0.816832  0.371794
2019-02-15 -0.869615 -0.499733 -0.172485 -1.308721  0.960749
2019-02-16 -0.079706  1.284381  1.449877  1.559430 -0.374694
2019-02-17  0.576903 -0.592522  0.889597  0.969139  0.096224
2019-02-18  1.810241 -1.505246  1.358606  1.096470 -0.426046
2019-02-19  0.272092  0.390804 -1.184750 -0.641831  1.063945
2019-02-20 -0.186324 -2.260274  2.080890 -0.231424  0.381548
2019-02-21 -2.634940  1.321969 -1.022110 -0.773333 -1.673571
2019-02-22 -0.572063 -0.365290 -0.572349  0.187006 -1.107939
2019-02-23  0.809245 -0.522017  0.729624  0.158454 -1.320872
2019-02-24 -0.303058 -0.335525  0.571005 -1.265099  1.051352
2019-02-25  0.580198  0.904637  1.022118  0.197767  0.194118
2019-02-26 -0.402234  0.997690 -0.001042 -0.459815  1.145586
2019-02-27 -0.416498  0.215989  0.719545  3.174480 -0.276651
2019-02-28  0.086500  0.282540  0.884520  0.330009 -1.487289
2019-03-01  0.669304  0.498369 -0.590588 -1.304093 -0.008996

In [22]:
df.shape

(60, 5)

In [23]:
df.head(3)

                   A         B         D         C         E
2019-01-01  0.111416  0.006918  1.588159  0.633591 -0.518574
2019-01-02 -1.518250  2.507258  0.702467  0.317387 -0.991721
2019-01-03  0.843329  0.417273  1.471881  0.092212  0.350613

In [24]:
df['F'] = 1

In [25]:
df.head(10)

                   A         B         D         C         E  F
2019-01-01  0.111416  0.006918  1.588159  0.633591 -0.518574  1
2019-01-02 -1.518250  2.507258  0.702467  0.317387 -0.991721  1
2019-01-03  0.843329  0.417273  1.471881  0.092212  0.350613  1
2019-01-04  0.155155  0.432690 -0.343179 -0.863025 -0.404969  1
2019-01-05  1.088454 -0.350057  1.541270  1.009635  0.850226  1
2019-01-06  1.603226  0.153579  1.565917  0.718555  1.816141  1
2019-01-07 -1.306833 -0.597524 -0.175347 -1.110990  0.467794  1
2019-01-08  1.055358  0.213915 -0.143741  1.571102 -0.781199  1
2019-01-09 -1.482818  0.661813  0.733995  0.397556  0.821253  1
2019-01-10  1.303259  0.392932  0.365818  0.086197  0.895103  1

In [26]:
df['G'] =[10, 3, 5, 7]

ValueError: ignored

In [27]:
df['G'] = range(60)

In [28]:
df.head(15)

                   A         B         D         C         E  F   G
2019-01-01  0.111416  0.006918  1.588159  0.633591 -0.518574  1   0
2019-01-02 -1.518250  2.507258  0.702467  0.317387 -0.991721  1   1
2019-01-03  0.843329  0.417273  1.471881  0.092212  0.350613  1   2
2019-01-04  0.155155  0.432690 -0.343179 -0.863025 -0.404969  1   3
2019-01-05  1.088454 -0.350057  1.541270  1.009635  0.850226  1   4
2019-01-06  1.603226  0.153579  1.565917  0.718555  1.816141  1   5
2019-01-07 -1.306833 -0.597524 -0.175347 -1.110990  0.467794  1   6
2019-01-08  1.055358  0.213915 -0.143741  1.571102 -0.781199  1   7
2019-01-09 -1.482818  0.661813  0.733995  0.397556  0.821253  1   8
2019-01-10  1.303259  0.392932  0.365818  0.086197  0.895103  1   9
2019-01-11 -0.624323 -0.510356  0.456074 -1.828303 -1.302972  1  10
2019-01-12  1.640171  0.622274 -1.158850  0.430788 -1.161643  1  11
2019-01-13  0.581331  1.125686 -0.866457  1.421796  0.353079  1  12
2019-01-14  0.434366  0.642006 -1.001932  0.223331 -1.322373  1  13
2019-01-15 -1.241906 -0.896917 -2.549503  0.115943  1.444284  1  14

In [29]:
df['Produto'] = df['A'] * df['B']

In [30]:
df.head(3)

                   A         B         D         C         E  F  G   Produto
2019-01-01  0.111416  0.006918  1.588159  0.633591 -0.518574  1  0  0.000771
2019-01-02 -1.518250  2.507258  0.702467  0.317387 -0.991721  1  1 -3.806645
2019-01-03  0.843329  0.417273  1.471881  0.092212  0.350613  1  2  0.351898

In [31]:
# df['DataAtualização'] = pd.to_datetime('now')

In [32]:
df

                   A         B         D         C         E  F   G   Produto
2019-01-01  0.111416  0.006918  1.588159  0.633591 -0.518574  1   0  0.000771
2019-01-02 -1.518250  2.507258  0.702467  0.317387 -0.991721  1   1 -3.806645
2019-01-03  0.843329  0.417273  1.471881  0.092212  0.350613  1   2  0.351898
2019-01-04  0.155155  0.432690 -0.343179 -0.863025 -0.404969  1   3  0.067134
2019-01-05  1.088454 -0.350057  1.541270  1.009635  0.850226  1   4 -0.381021
2019-01-06  1.603226  0.153579  1.565917  0.718555  1.816141  1   5  0.246223
2019-01-07 -1.306833 -0.597524 -0.175347 -1.110990  0.467794  1   6  0.780864
2019-01-08  1.055358  0.213915 -0.143741  1.571102 -0.781199  1   7  0.225757
2019-01-09 -1.482818  0.661813  0.733995  0.397556  0.821253  1   8 -0.981349
2019-01-10  1.303259  0.392932  0.365818  0.086197  0.895103  1   9  0.512092
2019-01-11 -0.624323 -0.510356  0.456074 -1.828303 -1.302972  1  10  0.318627
2019-01-12  1.640171  0.622274 -1.158850  0.430788 -1.161643  1  11  1.020635
2019-01-13  0.581331  1.125686 -0.866457  1.421796  0.353079  1  12  0.654396
2019-01-14  0.434366  0.642006 -1.001932  0.223331 -1.322373  1  13  0.278866
2019-01-15 -1.241906 -0.896917 -2.549503  0.115943  1.444284  1  14  1.113886
2019-01-16  1.835023  0.560078  1.032684  0.302270 -0.529789  1  15  1.027756
2019-01-17 -0.874358 -0.703602 -2.164161 -0.509257 -1.250895  1  16  0.615200
2019-01-18 -1.154140  0.857789  1.239455 -0.799702 -0.408749  1  17 -0.990009
2019-01-19  0.523384 -0.848025 -0.844232 -0.362599 -1.223686  1  18 -0.443842
2019-01-20  0.778159 -0.009133  0.552068  1.331865 -2.740306  1  19 -0.007107
2019-01-21  0.261236 -0.884125  0.573206 -0.532206 -0.127586  1  20 -0.230966
2019-01-22  0.844414  0.490242  0.209747  0.841251 -1.851385  1  21  0.413967
2019-01-23  2.018771  1.340353 -0.514892  1.110466 -1.214233  1  22  2.705867
2019-01-24 -0.590661  0.632784  1.419447 -0.540189  0.241935  1  23 -0.373761
2019-01-25  1.805676 -0.239450  1.185251 -0.166183 -1.004582  1  24 -0.432368
2019-01-26  1.058356  0.274076 -1.477420 -0.565588  0.914927  1  25  0.290070
2019-01-27 -1.010448 -0.733963  0.160791 -0.831296  0.361066  1  26  0.741631
2019-01-28 -0.227129  1.269629 -1.213567 -1.178905  1.167650  1  27 -0.288370
2019-01-29 -3.389752 -1.432752 -0.243193  0.811482 -0.838627  1  28  4.856674
2019-01-30  0.846061 -1.090074 -0.595651 -0.122081 -1.607270  1  29 -0.922269
2019-01-31 -1.210626 -0.351689  0.000788  0.249385 -0.221661  1  30  0.425763
2019-02-01  0.320558  1.315141 -1.112738  0.075485 -0.641175  1  31  0.421579
2019-02-02  0.002696 -0.733324  0.010175 -0.254468 -0.328669  1  32 -0.001977
2019-02-03 -0.559704 -0.760697 -0.340022 -0.526066  0.798391  1  33  0.425765
2019-02-04  1.396016 -1.232260  0.270611 -0.743717  0.439987  1  34 -1.720254
2019-02-05 -0.589496  0.162884 -0.787107 -0.009882  0.163886  1  35 -0.096020
2019-02-06 -0.012012 -0.556156  0.560739  0.600325  0.107971  1  36  0.006681
2019-02-07  0.145543  1.579913  1.543731 -2.356622  0.309235  1  37  0.229945
2019-02-08  0.950932 -0.321291 -0.907409  0.687715 -1.038975  1  38 -0.305526
2019-02-09  1.147952  0.581821  3.083746 -0.130997  1.105205  1  39  0.667902
2019-02-10  1.385582  0.804410 -0.958235 -0.798667  0.697343  1  40  1.114577
2019-02-11 -0.676924 -1.013777 -0.554140  0.468807 -0.901721  1  41  0.686250
2019-02-12 -1.296520 -0.938633  0.073211  1.146531  0.775687  1  42  1.216956
2019-02-13 -1.409668  3.257201 -0.372407  0.354055 -0.076574  1  43 -4.591572
2019-02-14 -0.511498 -2.189097 -0.466224  0.816832  0.371794  1  44  1.119720
2019-02-15 -0.869615 -0.499733 -0.172485 -1.308721  0.960749  1  45  0.434576
2019-02-16 -0.079706  1.284381  1.449877  1.559430 -0.374694  1  46 -0.102373
2019-02-17  0.576903 -0.592522  0.889597  0.969139  0.096224  1  47 -0.341828
2019-02-18  1.810241 -1.505246  1.358606  1.096470 -0.426046  1  48 -2.724858
2019-02-19  0.272092  0.390804 -1.184750 -0.641831  1.063945  1  49  0.106335
2019-02-20 -0.186324 -2.260274  2.080890 -0.231424  0.381548  1  50  0.421144
2019-02-21 -2.634940  1.321969 -1.022110 -0.773333 -1.673571  1  51 -3.483308
2019-02-22 -0.572063 -0.365290 -0.572349  0.187006 -1.107939  1  52  0.208969
2019-02-23  0.809245 -0.522017  0.729624  0.158454 -1.320872  1  53 -0.422439
2019-02-24 -0.303058 -0.335525  0.571005 -1.265099  1.051352  1  54  0.101684
2019-02-25  0.580198  0.904637  1.022118  0.197767  0.194118  1  55  0.524869
2019-02-26 -0.402234  0.997690 -0.001042 -0.459815  1.145586  1  56 -0.401305
2019-02-27 -0.416498  0.215989  0.719545  3.174480 -0.276651  1  57 -0.089959
2019-02-28  0.086500  0.282540  0.884520  0.330009 -1.487289  1  58  0.024440
2019-03-01  0.669304  0.498369 -0.590588 -1.304093 -0.008996  1  59  0.333560

In [33]:
# VISUALIZAR DADOS

In [35]:
df.head(2)

                   A         B         D         C         E  F  G   Produto
2019-01-01  0.111416  0.006918  1.588159  0.633591 -0.518574  1  0  0.000771
2019-01-02 -1.518250  2.507258  0.702467  0.317387 -0.991721  1  1 -3.806645

In [36]:
df.tail(2)

                   A         B         D         C         E  F   G  Produto
2019-02-28  0.086500  0.282540  0.884520  0.330009 -1.487289  1  58  0.02444
2019-03-01  0.669304  0.498369 -0.590588 -1.304093 -0.008996  1  59  0.33356

In [37]:
df.index

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07', '2019-01-08',
               '2019-01-09', '2019-01-10', '2019-01-11', '2019-01-12',
               '2019-01-13', '2019-01-14', '2019-01-15', '2019-01-16',
               '2019-01-17', '2019-01-18', '2019-01-19', '2019-01-20',
               '2019-01-21', '2019-01-22', '2019-01-23', '2019-01-24',
               '2019-01-25', '2019-01-26', '2019-01-27', '2019-01-28',
               '2019-01-29', '2019-01-30', '2019-01-31', '2019-02-01',
               '2019-02-02', '2019-02-03', '2019-02-04', '2019-02-05',
               '2019-02-06', '2019-02-07', '2019-02-08', '2019-02-09',
               '2019-02-10', '2019-02-11', '2019-02-12', '2019-02-13',
               '2019-02-14', '2019-02-15', '2019-02-16', '2019-02-17',
               '2019-02-18', '2019-02-19', '2019-02-20', '2019-02-21',
               '2019-02-22', '2019-02-23', '2019-02-24', '2019-02-25',
               '2019-02-26', '2019-02-27', '2019-02-28', '2019-03-01'],
              dtype='datetime64[ns]', freq='D')

In [38]:
df.columns

Index(['A', 'B', 'D', 'C', 'E', 'F', 'G', 'Produto'], dtype='object')

In [39]:
df.to_numpy()

array([[ 1.11415764e-01,  6.91822382e-03,  1.58815852e+00,
         6.33591163e-01, -5.18573926e-01,  1.00000000e+00,
         0.00000000e+00,  7.70799191e-04],
       [-1.51824984e+00,  2.50725847e+00,  7.02466973e-01,
         3.17387199e-01, -9.91720739e-01,  1.00000000e+00,
         1.00000000e+00, -3.80664478e+00],
       [ 8.43329426e-01,  4.17272794e-01,  1.47188087e+00,
         9.22116699e-02,  3.50613375e-01,  1.00000000e+00,
         2.00000000e+00,  3.51898426e-01],
       [ 1.55155175e-01,  4.32689795e-01, -3.43179449e-01,
        -8.63024752e-01, -4.04968775e-01,  1.00000000e+00,
         3.00000000e+00,  6.71340607e-02],
       [ 1.08845425e+00, -3.50057389e-01,  1.54127017e+00,
         1.00963491e+00,  8.50226295e-01,  1.00000000e+00,
         4.00000000e+00, -3.81021453e-01],
       [ 1.60322580e+00,  1.53579431e-01,  1.56591685e+00,
         7.18554807e-01,  1.81614125e+00,  1.00000000e+00,
         5.00000000e+00,  2.46222506e-01],
       [-1.30683252e+00, -5.97524403e-01, -1.75346931e-01,
        -1.11099028e+00,  4.67794358e-01,  1.00000000e+00,
         6.00000000e+00,  7.80864323e-01],
       [ 1.05535757e+00,  2.13915076e-01, -1.43740586e-01,
         1.57110208e+00, -7.81199163e-01,  1.00000000e+00,
         7.00000000e+00,  2.25756895e-01],
       [-1.48281757e+00,  6.61813483e-01,  7.33994679e-01,
         3.97555513e-01,  8.21252528e-01,  1.00000000e+00,
         8.00000000e+00, -9.81348660e-01],
       [ 1.30325946e+00,  3.92931998e-01,  3.65817882e-01,
         8.61974757e-02,  8.95102844e-01,  1.00000000e+00,
         9.00000000e+00,  5.12092342e-01],
       [-6.24322828e-01, -5.10356227e-01,  4.56074208e-01,
        -1.82830309e+00, -1.30297196e+00,  1.00000000e+00,
         1.00000000e+01,  3.18627043e-01],
       [ 1.64017077e+00,  6.22273556e-01, -1.15884969e+00,
         4.30788385e-01, -1.16164282e+00,  1.00000000e+00,
         1.10000000e+01,  1.02063490e+00],
       [ 5.81330701e-01,  1.12568583e+00, -8.66457245e-01,
         1.42179592e+00,  3.53079286e-01,  1.00000000e+00,
         1.20000000e+01,  6.54395733e-01],
       [ 4.34366387e-01,  6.42006375e-01, -1.00193164e+00,
         2.23330538e-01, -1.32237337e+00,  1.00000000e+00,
         1.30000000e+01,  2.78865989e-01],
       [-1.24190552e+00, -8.96916711e-01, -2.54950308e+00,
         1.15942592e-01,  1.44428442e+00,  1.00000000e+00,
         1.40000000e+01,  1.11388581e+00],
       [ 1.83502344e+00,  5.60077798e-01,  1.03268396e+00,
         3.02269782e-01, -5.29789041e-01,  1.00000000e+00,
         1.50000000e+01,  1.02775589e+00],
       [-8.74357739e-01, -7.03601967e-01, -2.16416052e+00,
        -5.09256755e-01, -1.25089516e+00,  1.00000000e+00,
         1.60000000e+01,  6.15199825e-01],
       [-1.15414016e+00,  8.57789090e-01,  1.23945534e+00,
        -7.99701513e-01, -4.08749232e-01,  1.00000000e+00,
         1.70000000e+01, -9.90008839e-01],
       [ 5.23383714e-01, -8.48024895e-01, -8.44232429e-01,
        -3.62598844e-01, -1.22368609e+00,  1.00000000e+00,
         1.80000000e+01, -4.43842419e-01],
       [ 7.78159175e-01, -9.13325592e-03,  5.52067857e-01,
         1.33186456e+00, -2.74030557e+00,  1.00000000e+00,
         1.90000000e+01, -7.10712689e-03],
       [ 2.61236305e-01, -8.84125487e-01,  5.73206299e-01,
        -5.32206169e-01, -1.27586178e-01,  1.00000000e+00,
         2.00000000e+01, -2.30965675e-01],
       [ 8.44413788e-01,  4.90241829e-01,  2.09747049e-01,
         8.41251159e-01, -1.85138543e+00,  1.00000000e+00,
         2.10000000e+01,  4.13966960e-01],
       [ 2.01877096e+00,  1.34035342e+00, -5.14892296e-01,
         1.11046566e+00, -1.21423272e+00,  1.00000000e+00,
         2.20000000e+01,  2.70586657e+00],
       [-5.90660655e-01,  6.32784266e-01,  1.41944718e+00,
        -5.40188616e-01,  2.41935033e-01,  1.00000000e+00,
         2.30000000e+01, -3.73760769e-01],
       [ 1.80567611e+00, -2.39449521e-01,  1.18525114e+00,
        -1.66183268e-01, -1.00458194e+00,  1.00000000e+00,
         2.40000000e+01, -4.32368278e-01],
       [ 1.05835636e+00,  2.74075691e-01, -1.47742011e+00,
        -5.65587985e-01,  9.14926587e-01,  1.00000000e+00,
         2.50000000e+01,  2.90069750e-01],
       [-1.01044807e+00, -7.33962933e-01,  1.60790557e-01,
        -8.31295676e-01,  3.61066459e-01,  1.00000000e+00,
         2.60000000e+01,  7.41631431e-01],
       [-2.27129043e-01,  1.26962941e+00, -1.21356732e+00,
        -1.17890508e+00,  1.16764998e+00,  1.00000000e+00,
         2.70000000e+01, -2.88369712e-01],
       [-3.38975229e+00, -1.43275184e+00, -2.43192527e-01,
         8.11482074e-01, -8.38626976e-01,  1.00000000e+00,
         2.80000000e+01,  4.85667383e+00],
       [ 8.46061175e-01, -1.09007395e+00, -5.95651460e-01,
        -1.22080832e-01, -1.60726967e+00,  1.00000000e+00,
         2.90000000e+01, -9.22269251e-01],
       [-1.21062553e+00, -3.51688776e-01,  7.88293098e-04,
         2.49384574e-01, -2.21661150e-01,  1.00000000e+00,
         3.00000000e+01,  4.25763411e-01],
       [ 3.20558098e-01,  1.31514141e+00, -1.11273837e+00,
         7.54846885e-02, -6.41175487e-01,  1.00000000e+00,
         3.10000000e+01,  4.21579230e-01],
       [ 2.69606399e-03, -7.33323595e-01,  1.01749640e-02,
        -2.54468250e-01, -3.28669247e-01,  1.00000000e+00,
         3.20000000e+01, -1.97708734e-03],
       [-5.59704159e-01, -7.60697056e-01, -3.40022020e-01,
        -5.26066393e-01,  7.98391401e-01,  1.00000000e+00,
         3.30000000e+01,  4.25765306e-01],
       [ 1.39601586e+00, -1.23225975e+00,  2.70610682e-01,
        -7.43717281e-01,  4.39987243e-01,  1.00000000e+00,
         3.40000000e+01, -1.72025416e+00],
       [-5.89495593e-01,  1.62884459e-01, -7.87106553e-01,
        -9.88168566e-03,  1.63885700e-01,  1.00000000e+00,
         3.50000000e+01, -9.60196707e-02],
       [-1.20119925e-02, -5.56155810e-01,  5.60739370e-01,
         6.00324745e-01,  1.07970713e-01,  1.00000000e+00,
         3.60000000e+01,  6.68053939e-03],
       [ 1.45543014e-01,  1.57991344e+00,  1.54373068e+00,
        -2.35662241e+00,  3.09235425e-01,  1.00000000e+00,
         3.70000000e+01,  2.29945364e-01],
       [ 9.50932283e-01, -3.21290966e-01, -9.07408875e-01,
         6.87715140e-01, -1.03897507e+00,  1.00000000e+00,
         3.80000000e+01, -3.05525952e-01],
       [ 1.14795221e+00,  5.81820624e-01,  3.08374573e+00,
        -1.30996751e-01,  1.10520469e+00,  1.00000000e+00,
         3.90000000e+01,  6.67902271e-01],
       [ 1.38558201e+00,  8.04410366e-01, -9.58235277e-01,
        -7.98666995e-01,  6.97343246e-01,  1.00000000e+00,
         4.00000000e+01,  1.11457653e+00],
       [-6.76923952e-01, -1.01377661e+00, -5.54140114e-01,
         4.68807051e-01, -9.01721453e-01,  1.00000000e+00,
         4.10000000e+01,  6.86249670e-01],
       [-1.29651955e+00, -9.38632880e-01,  7.32107664e-02,
         1.14653116e+00,  7.75686809e-01,  1.00000000e+00,
         4.20000000e+01,  1.21695588e+00],
       [-1.40966793e+00,  3.25720104e+00, -3.72407367e-01,
         3.54055160e-01, -7.65739525e-02,  1.00000000e+00,
         4.30000000e+01, -4.59157184e+00],
       [-5.11498378e-01, -2.18909692e+00, -4.66224294e-01,
         8.16832495e-01,  3.71793920e-01,  1.00000000e+00,
         4.40000000e+01,  1.11971953e+00],
       [-8.69615100e-01, -4.99733353e-01, -1.72484710e-01,
        -1.30872095e+00,  9.60748793e-01,  1.00000000e+00,
         4.50000000e+01,  4.34575670e-01],
       [-7.97062634e-02,  1.28438132e+00,  1.44987720e+00,
         1.55943049e+00, -3.74693755e-01,  1.00000000e+00,
         4.60000000e+01, -1.02373236e-01],
       [ 5.76903244e-01, -5.92521796e-01,  8.89596993e-01,
         9.69139322e-01,  9.62244359e-02,  1.00000000e+00,
         4.70000000e+01, -3.41827746e-01],
       [ 1.81024058e+00, -1.50524613e+00,  1.35860640e+00,
         1.09646968e+00, -4.26045896e-01,  1.00000000e+00,
         4.80000000e+01, -2.72485763e+00],
       [ 2.72092484e-01,  3.90803962e-01, -1.18474952e+00,
        -6.41830999e-01,  1.06394544e+00,  1.00000000e+00,
         4.90000000e+01,  1.06334821e-01],
       [-1.86324489e-01, -2.26027364e+00,  2.08088953e+00,
        -2.31423795e-01,  3.81547737e-01,  1.00000000e+00,
         5.00000000e+01,  4.21144331e-01],
       [-2.63494018e+00,  1.32196863e+00, -1.02211027e+00,
        -7.73333295e-01, -1.67357109e+00,  1.00000000e+00,
         5.10000000e+01, -3.48330828e+00],
       [-5.72063461e-01, -3.65290383e-01, -5.72348555e-01,
         1.87005771e-01, -1.10793864e+00,  1.00000000e+00,
         5.20000000e+01,  2.08969281e-01],
       [ 8.09244579e-01, -5.22016633e-01,  7.29624467e-01,
         1.58453563e-01, -1.32087244e+00,  1.00000000e+00,
         5.30000000e+01, -4.22439131e-01],
       [-3.03057622e-01, -3.35525496e-01,  5.71005323e-01,
        -1.26509931e+00,  1.05135225e+00,  1.00000000e+00,
         5.40000000e+01,  1.01683559e-01],
       [ 5.80197895e-01,  9.04637173e-01,  1.02211815e+00,
         1.97767004e-01,  1.94118209e-01,  1.00000000e+00,
         5.50000000e+01,  5.24868583e-01],
       [-4.02234083e-01,  9.97689565e-01, -1.04180768e-03,
        -4.59814723e-01,  1.14558620e+00,  1.00000000e+00,
         5.60000000e+01, -4.01304747e-01],
       [-4.16497880e-01,  2.15988501e-01,  7.19545452e-01,
         3.17448043e+00, -2.76650930e-01,  1.00000000e+00,
         5.70000000e+01, -8.99587530e-02],
       [ 8.64999713e-02,  2.82539857e-01,  8.84520331e-01,
         3.30008543e-01, -1.48728919e+00,  1.00000000e+00,
         5.80000000e+01,  2.44396895e-02],
       [ 6.69303875e-01,  4.98368567e-01, -5.90587890e-01,
        -1.30409331e+00, -8.99639579e-03,  1.00000000e+00,
         5.90000000e+01,  3.33560013e-01]])

In [40]:
df.T

         2019-01-01  2019-01-02  2019-01-03  ...  2019-02-27  2019-02-28  2019-03-01
A          0.111416   -1.518250    0.843329  ...   -0.416498    0.086500    0.669304
B          0.006918    2.507258    0.417273  ...    0.215989    0.282540    0.498369
D          1.588159    0.702467    1.471881  ...    0.719545    0.884520   -0.590588
C          0.633591    0.317387    0.092212  ...    3.174480    0.330009   -1.304093
E         -0.518574   -0.991721    0.350613  ...   -0.276651   -1.487289   -0.008996
F          1.000000    1.000000    1.000000  ...    1.000000    1.000000    1.000000
G          0.000000    1.000000    2.000000  ...   57.000000   58.000000   59.000000
Produto    0.000771   -3.806645    0.351898  ...   -0.089959    0.024440    0.333560

[8 rows x 60 columns]